import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google"; 
import { TRPCReactProvider } from "~/trpc/react";
import { DashboardSidebar } from "~/components/sidebar";
import { DashboardHeader } from "~/components/header";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) { 
    
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <div className="flex h-screen bg-background">
            {/* Sidebar */}
            <DashboardSidebar />

            {/* Main Content */}
            <div className="flex-1 flex flex-col overflow-hidden">
              {/* Header */}
              <DashboardHeader />

              {/* Dashboard Content */}
              <main className="flex-1 overflow-y-auto p-6">
                {children}
              </main>
            </div>
          </div> 
        </TRPCReactProvider>
      </body>
    </html>
  );
}
